RP2040: Better detection of flash size
blackmagic-debug/blackmagic pull request #1058
Opened 2022-06-16 18:22 UTC by jamesturton

Following on from the discussions in #1045, this PR aims to provide a better way to identify the size of the SPI flash connected to the RP2040. It does this in two steps:

First, look for repeating sectors in the flash region. This was the original approach that was used and should work if a valid program is loaded in memory, but it will fail if the flash memory is blank, or written with other uniform data. The idea is that if you attempt to read an address outside of the valid flash sector, you will get the data from the start of the sector. 

The second attempt is a bit more aggressive: trying to reading the JEDEC ID of the flash chip. This will interrupt the flash XIP and revert back to SPI mode, but we assume that there is no valid program stored in the memory, otherwise we should have been able to detect it in the previous method. Once we have the JEDEC ID, we can get the log base 2 size of the flash chip from it's second byte.

2022-06-16 19:30 UTC, dragonmux requested changes
This is looking great - just a couple of things highlighted in the review. Once those are addressed and we've tested this on real hardware, we'll merge this ASAP. Good job!

2022-06-16 19:30 UTC, dragonmux commented on src/target/rp.c
> +	for (int count = 0; (count < 4); count++)
no need for the extra () here as the comparison binds tighter than the ;'s do. Likewise size_t rather than int - no point having this be signed.

2022-06-16 19:30 UTC, dragonmux commented on src/target/rp.c
> +	int i;
size_t as no point having this be signed

2022-06-17 07:43 UTC, jamesturton commented
Thanks for the review @dragonmux! Hopefully I've addressed everything you mentioned above

2022-06-17 08:21 UTC, jamesturton reviewed
Resolved in 50e43e7

2022-06-17 11:00 UTC, dragonmux approved these changes
LGTM, we'll build and test this on our local RP2040 hardware and merge if it all works properly

2022-06-25 00:43 UTC, dragonmux commented
We can now confirm this code works. Merging

2022-06-25 00:44 UTC, merged