Move all files from "pc" to "hosted" and rename "cl_utils.* to "cli.*.
blackmagic-debug/blackmagic pull request #1059
Opened 2022-06-18 22:32 UTC by sidprice

Built and tested on Windows 11, not built for Linux.

2022-06-19 02:48 UTC, dragonmux requested changes
There's only one thing we spotted - this otherwise look great. This will be ready for merge once that one item is addressed.

2022-06-19 13:38 UTC, sidprice commented on .gitignore
> +refs/
The refs folder contains the text-based help files I have been preparing for the update of BMDA "-h" option.

2022-06-19 13:43 UTC, dragonmux commented on .gitignore
> +refs/
ah, ok.. given that's something local to you and will never see the repo, please remove this ignore from the patchset (you can have it locally, that's understandable and fine, just.. not in repo)

2022-06-19 13:48 UTC, sidprice commented
@dragonmux Sure, however, I don't know how to do that, i.e. maintain a local .gitignore?

2022-06-19 13:58 UTC, dragonmux commented
To accomplish this, what you'll need to do is first remove the change to the ignore, `git add .gitignore`, then commit it as a fixup to the commit it came in on (`git commit --fixup 81b804a`) - once you've done that you can edit the change back in but leave it not-added (`git add -a` is frowned on anyway so as long as you don't use that to add changes, it won't be a problem).

Once all that's done, `git rebase -i master --autosquash` to apply the fixup and then `git push -f` to update the PR.

2022-06-19 14:11 UTC, sidprice commented
Sounds awfully complicated ... why don't I just fix .gitignore and move my refs folder outside the repo?

2022-06-19 14:14 UTC, dragonmux commented
That'd be fine, though the fixup process is similar (the commit and rebase probably seem scary, but they're really not that bad and Git'll guide you through it)

2022-06-19 14:20 UTC, dragonmux commented
Please rebase the gitignore fix as a fixup commit to 81b804a as this introduces noise which can be easily avoided. `git rebase -i master` and move efc5b64 just under 81b804a in the text editor, changing the 'pick' prefix to 'f'. A force-push will be required after.

2022-06-19 14:25 UTC, sidprice commented
I am way out of my depth with git here, quite lost.

2022-06-19 14:30 UTC, dragonmux commented
That problem is why we suggested using a fixup commit as then the tools automate things - `git reset HEAD~` to go back one commit, `git add .gitignore` to stage the ignore fix, `git commit --fixup 81b804a` to commit it as a fixup for 81b804a that can be automatically applied, then `git rebase master --autosquash` to automatically apply it. `git push -f` to force push on completion - please trust us that this is correct and will work. Exact command lines to run given

2022-06-19 14:42 UTC, sidprice commented
OK:

PS D:\DataRoot\Projects\blackmagic> git reset HEAD                           
PS D:\DataRoot\Projects\blackmagic> git add .gitignore
PS D:\DataRoot\Projects\blackmagic> git commit --fixup 81b804a
On branch BMDA_CLI_help
Your branch is up to date with 'origin/BMDA_CLI_help'.

nothing to commit, working tree clean
PS D:\DataRoot\Projects\blackmagic>

2022-06-19 14:43 UTC, dragonmux commented
you missed the ~ off HEAD.

2022-06-19 14:45 UTC, sidprice commented
OK, seems better :)

2022-06-19 14:49 UTC, dragonmux submitted a review, later dismissed
LGTM. We saw the CI build passed so we'll merge this.

2022-06-26 07:18 UTC, dragonmux commented
@sidprice went to go merge this and spotted that the `git rebase -i master --autosquash` step hadn't been done, so the fixup commit is still present.

Could we get you to run that step and do a `git push -f` please? Once we've seen that happen, we'll merge this.

2022-06-26 16:04 UTC, dragonmux approved these changes
LGTM, thank you sid! Merging.

2022-06-26 16:04 UTC, merged