cleanup flash read write return type
blackmagic-debug/blackmagic pull request #1211
Opened 2022-08-24 13:17 UTC by perigoso

follow up for #1205, this is a separate PR in the interest of keeping #1205 briefer and easier to review, these changes are also not required for those changes

This touches a lot of code so a thorough review is needed to make sure current behaviour is maintaned

## Your checklist for this pull request

* [x] I've read the [Code of Conduct](https://github.com/blackmagic-debug/blackmagic/blob/main/CODE_OF_CONDUCT.md)
* [x] I've read the [guidelines for contributing](https://github.com/blackmagic-debug/blackmagic/blob/main/CONTRIBUTING.md) to this repository
* [x] It builds for hardware native (`make PROBE_HOST=native`)
* [x] It builds as BMDA (`make PROBE_HOST=hosted`)
* [ ] I've tested it to the best of my ability
* [x] My commit messages provide a useful short description of what the commits do

## Closing issues

2022-08-24 16:51 UTC, perigoso commented
note to self, fix the author email

2022-08-25 00:09 UTC, dragonmux requested changes
This is generally looking really good and certainly improves the consistency of the code and its understandability.

There are a few small things that stuck out in review such as a couple of missed return statements and some return ifs with explicit true/false return paths that can be elided into a single return statement. With those fixed, this looks ready for merge

2022-08-25 00:09 UTC, dragonmux commented on src/target/sam3x.c
>  	if(sam_flash_cmd(t, base, sf->write_cmd, chunk))
As this if is immediately followed by returns on both branches, we'd suggest it should be replaced by a direct `return !sam_flash_cmd();` (clang-tidy should say something to this effect too)

2022-08-25 00:09 UTC, dragonmux commented on src/target/sam4l.c
> +	if (sam4l_flash_command(t, page, FLASH_CMD_WP))
As this if is immediately followed by returns on both branches, we'd suggest it should be replaced by a direct `return !sam4l_flash_command();` (clang-tidy should say something to this effect too)

2022-08-25 00:09 UTC, dragonmux commented on src/target/stm32f4.c
> +		return false;
Can the returns here be elided? looks like it could be `return !(sr & SR_ERROR_MASK);`

2022-08-25 00:09 UTC, dragonmux commented on src/target/stm32f4.c
>  	if(sr & SR_ERROR_MASK) {
Missing space between if and (

2022-08-25 00:09 UTC, dragonmux commented on src/target/stm32f4.c
> +			return false;
Same comment as above about return elision

2022-08-25 00:09 UTC, dragonmux commented on src/target/stm32g0.c
> +	return (status & FLASH_SR_ERROR_MASK) ? false : true;
This can be converted from a ternary, please do so.

2022-08-25 00:09 UTC, dragonmux commented on src/target/stm32l0.c
The return just above this can and should be elided and is currently the wrong type

2022-08-25 00:09 UTC, dragonmux commented on src/target/stm32l0.c
>  	return 0;
`return true;`?

2022-08-25 00:09 UTC, dragonmux commented on src/target/stm32l0.c
>  	if ((sr & STM32Lx_NVM_SR_ERR_M) || !(sr & STM32Lx_NVM_SR_EOP) || target_check_error(t))
This if/return looks like it can and should be elided

2022-08-25 00:09 UTC, dragonmux commented on src/target/stm32l0.c
>  	if ((sr & STM32Lx_NVM_SR_ERR_M) || !(sr & STM32Lx_NVM_SR_EOP) || target_check_error(t))
Please elide the if/return

2022-08-25 00:09 UTC, dragonmux commented on src/target/stm32l0.c
>  	if ((sr & STM32Lx_NVM_SR_ERR_M) || !(sr & STM32Lx_NVM_SR_EOP) || target_check_error(t))
Same comment as above

2022-08-25 00:09 UTC, dragonmux commented on src/target/stm32l4.c
>  	if (stm32l4_flash_read32(t, FLASH_SR) & FLASH_SR_ERROR_MASK)
Return elision

2022-08-25 00:09 UTC, dragonmux commented on src/target/stm32l4.c
> +		return false;
Return elision

2022-08-25 16:49 UTC, dragonmux requested changes
This is looking much better, we spotted 3 things this time through and they're all minor - think we'll get this landed today if you can get these items addressed :)

2022-08-25 16:49 UTC, dragonmux commented on src/target/stm32f4.c
> +		tc_printf(t, "\b%c", spinner[spinindex++ % 4]);
With this restructure, this can be replaced with `target_print_progress` which would eliminate another of these manual spinner implementations.

2022-08-25 16:49 UTC, dragonmux commented on src/target/stm32l4.c
> +	if(!stm32l4_flash_busy_wait(t))
Missing space between `if` and `(`

2022-08-25 16:49 UTC, dragonmux commented on src/target/rp.c
> +	bool ret = ((dbg_regs[REG_PC] & ~1) == (ps->rom_debug_trampoline_end & ~1));
the outer parens can and should be stripped

2022-08-25 20:16 UTC, dragonmux approved these changes
LGTM, testing on a couple of targets then merging.

2022-08-25 20:52 UTC, perigoso commented
I have tested this on EFM32 and incoming Renesas

2022-08-25 22:10 UTC, merged