stm32wx: Fix device detection broken since ce6477886f
blackmagic-debug/blackmagic pull request #1240
Opened 2022-09-14 14:12 UTC by UweBonnes

On STM32 DPv2 devices contain a DP_TARGETID with a zero added compared to the Romtable ID. In the DPIDR TARGETID rework around ce6477886f these IDs where changed for STM32H7 but not for STM32Wx.

## Detailed description

Get STM32Wx devices recognized by their DPIDR TARGETID by the needed change.

## Your checklist for this pull request

* [ x] I've read the [Code of Conduct](https://github.com/blackmagic-debug/blackmagic/blob/main/CODE_OF_CONDUCT.md)
* [ x] I've read the [guidelines for contributing](https://github.com/blackmagic-debug/blackmagic/blob/main/CONTRIBUTING.md) to this repository
* [ x] It builds for hardware native (`make PROBE_HOST=native`)
* [ x] It builds as BMDA (`make PROBE_HOST=hosted`)
* [x ] I've tested it to the best of my ability
* [x ] My commit messages provide a useful short description of what the commits do

## Closing issues

2022-09-14 14:51 UTC, dragonmux requested changes
Thank you for the contribution. Pleased to get more of the IDs sorted out after the ADIv5 compliance overhaul. We have a couple of small nitpicks we'd like addressed then we'll merge.

2022-09-14 15:05 UTC, dragonmux commented on src/target/stm32l4.c
> +	ID_STM32L55  = 0x472u, /* RM0438, Rev.4, DP_TARGETIDR is 0! */
ok, no worries - glad we asked for a clarification.

2022-09-15 16:56 UTC, UweBonnes commented
> is the ID_STM32L55 being 0 a problem? does it probe it correctly? a special case can be made and use the ap part no if necessary
Yes, it probes correct. And the 0 in DPIDR TARGETID is an omission on  the ST side. it is documented in the RM, but not seen as an errata by ST.
So falling back to the RomTable ID is the right thing here.

2022-09-15 17:57 UTC, dragonmux commented
We're happy to merge this once the outstanding review item is seen to - page numbers for a better explanatory comment, or put the comments back as the addition doesn't add anything of meaning to a reader not already deeply aware of what's going on here (and even if they are it's still super cryptic). See the above unresolved review item.

2022-09-15 19:34 UTC, UweBonnes commented
Removed the added comment.

2022-09-15 20:39 UTC, dragonmux commented
The review comment was for lines 150 and 151 too - please adjust those comments too. We'll even settle for a long-form explanation comment preceding those two lines, just as long as it's less cryptic than what's there now.

2022-09-16 10:24 UTC, UweBonnes commented
I took another approach, simplifying the code and keeping the old numbers.

2022-11-20 04:24 UTC, esden commented
I have just merged #1305 that provides an alternate, cleaned up and better documented implementation using the original approach from this PR. Please test the code in main and report if there are any issues.

2022-11-20 04:24 UTC, closed without merging