rtt: fix #1248, RTT for F072 (STM32F072) platform not working
blackmagic-debug/blackmagic pull request #1276
Opened 2022-10-27 11:12 UTC by koendv

## Detailed description

Tentative fix, issue "RTT for F072 (STM32F072) platform not working #1248."

The problem seems to be two errors:

- the nrf52 target announces more ram to gdb than physically present,
  and bmp hangs when rtt reads ram that is not physically present.
  target announcing the exact amount of ram is not practical.
  solution: add an option to restrict the address range rtt searches.
  ``mon rtt ram startaddress stopaddress``
- current rtt fetches address and size of circular buffer once, at initialisation, and head and tail pointers afterwards.
  if target software modifies buffer address or buffer size after rtt initialisation, bmp has out-of-date pointers to rtt circular buffers.
  solution: before accessing rtt circular buffers on target, each time fetch full control block from target. check rtt control block present and not corrupted.

Additionally:
- cosmetic changes:
  in "mon rtt status" change `ident "off"` to `ident off`
  in "mon rtt cblock" show head and tail values, not head and tail addresses; more intuitive.
- changed variable names etc. as suggested in code review

This PR has been tested on blackpillv2; needs to be tested on F072.

## Your checklist for this pull request

* [x] I've read the [Code of Conduct](https://github.com/blackmagic-debug/blackmagic/blob/main/CODE_OF_CONDUCT.md)
* [x] I've read the [guidelines for contributing](https://github.com/blackmagic-debug/blackmagic/blob/main/CONTRIBUTING.md) to this repository
* [x] It builds for hardware native (`make PROBE_HOST=native`)
* [x] It builds as BMDA (`make PROBE_HOST=hosted`)
* [x] I've tested it to the best of my ability
* [x] My commit messages provide a useful short description of what the commits do

## Closing issues

2022-10-28 12:02 UTC, dragonmux requested changes
Thank you for the contribution! This is shaping up well. We've spotted mostly stylistic things in the review with only one organisational point we'd like addressed.

2022-10-28 12:02 UTC, dragonmux commented on src/rtt.c
> +			uint32_t rtt_cblock_size = (sizeof rtt_channel[0]) * (rtt_num_up_chan + rtt_num_down_chan);
`sizeof(rtt_channel[0])` which also removes the outer parens around the expression

2022-10-28 12:02 UTC, dragonmux commented on src/rtt.c
> +						if (i < rtt_num_up_chan) {
Please remove the `{}`'s

2022-10-28 12:02 UTC, dragonmux commented on src/rtt.c
> +						if (v == RTT_OK) rtt_busy = true;
Run `clang-format`. These must be written as:
```c
if (v == RTT_OK)
    rtt_busy = true;
```
etc

2022-10-30 11:26 UTC, koendv commented
The comment about target_mem_access_needs_halt() to the target layer is correct. But I would prefer if the riscv branch was asked their opinion, as the code is specific to that target.

2022-10-30 13:41 UTC, dragonmux commented
We're the one working on making the RISC-V support PR-able - see branch feature/risc-v - and we're the maintainer telling you to put that function in the target layer. RISC-V is just as bound as anything else to the standards of code organisation the project has and if it's doing bad things we'll be fixing them before the final PR for v2.0.

2022-10-30 19:02 UTC, dragonmux commented on src/command.c
> +		rtt_flag_ram = (cnt1 == 1) && (cnt2 == 1) && (rtt_ram_end > rtt_ram_start);
To clarify, we're saying please rewrite this to `rtt_flag_ram = cnt1 == 1 && cnt2 == 1 && rtt_ram_end > rtt_ram_start;` so the GCC warning about accidental assignment in a comparison context is enabeld

2022-10-31 22:26 UTC, dragonmux requested changes
This is looking much better, thank you! There are still a couple of additional items outstanding from the first review and a couple more things that re-reviewing picked up, but this looks technically good and stylistically much more consistent.

We look forward to being able to merge this soon

2022-10-31 22:26 UTC, dragonmux commented on src/command.c
> +	} else if ((argc == 2) && strncmp(argv[1], "disabled", command_len) == 0) {
Please remove the extra parentheses from around the argc comparison here, and in the "status" block

2022-10-31 22:26 UTC, dragonmux commented on src/rtt.c
> +	t = 0;
This looks like a redundant assignment as it's already taken care of by line 91?

2022-10-31 22:26 UTC, dragonmux commented on src/rtt.c
> +				uint32_t cb_addr = addr + offset;
`const` or perhaps even merge the calculation into the return statement, dropping the {}'s for the if block?

2022-11-01 09:58 UTC, koendv commented
OK. That ought to do it, I think.

2022-11-01 17:18 UTC, dragonmux commented on src/rtt.c
> +	while ((next_head = ((rtt_channel[i].head + 1) % rtt_channel[i].buf_size)) != rtt_channel[i].tail && (ch = rtt_getchar()) != -1) {
We'll note this has not been fixed, but we'll go with the change as it is and make this not block. If you figure out a way to express this while loop condition more simply with the assignments done outside the condition body, please open another PR to address it. If not, we'll give it a try on the clean-up branches we're working on. If we manage to figure something out, we'll ping you to test it and sanity check it.

2022-11-01 17:19 UTC, dragonmux approved these changes
LGTM! Thank you for your hard work and bearing with us. Merging

2022-11-01 17:19 UTC, merged