FIX: Attaching to NRF Control Access Port Targets
blackmagic-debug/blackmagic pull request #1391
Opened 2023-02-19 17:00 UTC by TheyCallMeNobody

## Detailed description

This is a fix for a problem, which occured when trying to connect to the Control Access Port Targets on NRF52 chips: After attaching, it ran into an endless loop, because the CAP is no real CPU core and therefore no CPU Register Read is implemented. The fix adds the case, when 0 registers are available and respons to GDB by sending an dummy register with the value 'XX', which indicates, that the register value hasn't been collected.
This check is implemented when handling the 'g' packet.

## Your checklist for this pull request

* [X] I've read the [Code of Conduct](https://github.com/blackmagic-debug/blackmagic/blob/main/CODE_OF_CONDUCT.md)
* [X] I've read the [guidelines for contributing](https://github.com/blackmagic-debug/blackmagic/blob/main/CONTRIBUTING.md) to this repository
* [X] It builds for hardware native (`make PROBE_HOST=native`)
* [X] It builds as BMDA (`make PROBE_HOST=hosted`)
* [X] I've tested it to the best of my ability
* [X] My commit messages provide a useful short description of what the commits do

## Closing issues

fixes [#1353](https://github.com/blackmagic-debug/blackmagic/issues/1353)

2023-02-19 23:01 UTC, dragonmux requested changes
This is actually quite close to the fix that was talked about on the BMP channel on Discord, however there's a couple of small changes we'd like to see made before we merge the patch - one of them is formatting, and stylistic, the other is functional as the fix in 'g' handling may not work across GDBs and we actually also need to handle the 'p' and 'P' packets better to guarantee a lack of issues across versions etc.

With these items fixed, we're happy to merge this.

Understanding that the review might be a little difficult to fully grok, here's the version that was batted about on Discord which we'd planned to patch in, showing what we mean:

```c
        const size_t regs_size = target_regs_size(cur_target);
        if (regs_size) {
            uint8_t gp_regs[regs_size];
            target_regs_read(cur_target, gp_regs);
            gdb_putpacket(hexify(pbuf, gp_regs, regs_size), regs_size << 1U);
        } else
            gdb_putpacketz("00");
        break;
```

For the 'p' and 'P' packets, a check that t->reg_read and t->reg_write is not NULL before invoking the normal handler w/ a similar single-byte-0 response when they are, would be an appropriate fix.

2023-02-21 00:37 UTC, dragonmux commented on src/gdb_main.c
> +			gdb_putpacketz("00");
This isn't a valid response for 'G' to make per [GDB's docs on the remote protocol](https://docs.jade.fyi/gnu/gdb/gdb.html#index-G-packet); We have two options available here, either returning an error code such as "EFF", or returning "OK" and pretending it worked - we're inclined to the latter, which allows this to be simplified by moving the gdb_putpacketz() below the if block and drop the else.

2023-02-21 00:40 UTC, dragonmux commented on src/gdb_main.c
> +			gdb_putpacketz("00");
This [suffers the same response problem](https://docs.jade.fyi/gnu/gdb/gdb.html#index-P-packet) and we're going to suggest the same thing here with replying with `gdb_putpacketz("OK")` and pretending the write worked

2023-02-21 11:50 UTC, TheyCallMeNobody commented
I hope I changed everything in git correctly

2023-02-21 21:45 UTC, merged