Renesas: general renesas cleanups
blackmagic-debug/blackmagic pull request #1451
Opened 2023-04-11 23:41 UTC by perigoso

A couple generic cleanups, initially motivated by going through Renesas documentation.

Please hold on merging, I committed with work credentials, and won't be able to fix until tomorrow.

## Detailed description

## Your checklist for this pull request

* [x] I've read the [Code of Conduct](https://github.com/blackmagic-debug/blackmagic/blob/main/CODE_OF_CONDUCT.md)
* [x] I've read the [guidelines for contributing](https://github.com/blackmagic-debug/blackmagic/blob/main/CONTRIBUTING.md) to this repository
* [ ] It builds for hardware native (`make PROBE_HOST=native`)
* [ ] It builds as BMDA (`make PROBE_HOST=hosted`)
* [ ] I've tested it to the best of my ability
* [x] My commit messages provide a useful short description of what the commits do

## Closing issues

2023-04-13 19:01 UTC, dragonmux requested changes
Only spotted one potential misstep in this PR, otherwise it all looks good. Once the review point is addressed, we're happy to merge this.

Thanks for the contribution Perigoso!

2023-04-14 01:05 UTC, perigoso commented on src/target/renesas.c
> +		memset(pnr + 13U, '\x20', 3);
This change was less about correctness, and more about intent, shows we are populating the 3 last bytes with the space character and not with a 0x20 hex which where it comes from is not immediately clear
that said this isn't much of an improvement (maybe worse lol?), maybe I should use the actual space char instead `' '`

2023-04-14 02:44 UTC, dragonmux commented on src/target/renesas.c
> +		memset(pnr + 13U, '\x20', 3);
Ah, yes, that's a fair call - in that case, using an actual space character literal makes considerably more sense in context.

2023-04-14 16:39 UTC, perigoso commented on src/target/renesas.c
> +		memset(pnr + 13U, '\x20', 3);
Opted to just add an extra comment for context

2023-04-15 05:58 UTC, dragonmux approved these changes
LGTM, as this is mostly `const`-correctness and comments cleanup we'll merge this and anyone using the Renesas support who finds it breaks because of this can open an issue ticket.

2023-04-15 05:59 UTC, merged