Simplify ST-Link and JLink USB code
blackmagic-debug/blackmagic pull request #1480
Opened 2023-04-29 04:59 UTC by zyp

## Detailed description

This is the followup to #1478, bringing the same simplification to ST-Link and JLink USB interface drivers.

Not yet tested on hardware.

## Your checklist for this pull request

* [x] I've read the [Code of Conduct](https://github.com/blackmagic-debug/blackmagic/blob/main/CODE_OF_CONDUCT.md)
* [x] I've read the [guidelines for contributing](https://github.com/blackmagic-debug/blackmagic/blob/main/CONTRIBUTING.md) to this repository
* [x] It builds for hardware native (`make PROBE_HOST=native`)
* [x] It builds as BMDA (`make PROBE_HOST=hosted`)
* [x] I've tested it to the best of my ability
* [x] My commit messages provide a useful short description of what the commits do

## Closing issues

2023-04-29 05:07 UTC, dragonmux requested changes
This is a fantastic simplification! We'll test this after getting some sleep. Many thanks zyp.

The only items we've spotted in review are some possibly missing `return false;` and one now excessive set of braces. With those fixed and after a successful test, we'll be happy to merge this.

2023-04-29 05:07 UTC, dragonmux commented on src/platforms/hosted/stlinkv2.c
>  	}
Does this not still need to return false when triggered?

2023-04-29 05:07 UTC, dragonmux commented on src/platforms/hosted/jlink.c
>  	}
Does this not need to return false when triggered?

2023-04-29 05:07 UTC, dragonmux commented on src/platforms/hosted/jlink.c
> +	if (!claim_jlink_interface(info)) {
The {}'s are now excess here, please remove them

2023-04-29 20:23 UTC, dragonmux approved these changes
LGTM, we'll merge this after getting it tested.

2023-04-29 23:27 UTC, dragonmux commented
ST-Link tested working

2023-05-03 22:26 UTC, perigoso approved these changes
Tested with a JLink V8 and a JLink OB (BRD2207A)

There seem to be issues with the JLink code, getting libusb errors with both but looks unrelated to the changeset as behavior is unchanged with the base commit
I was able to connect and run *some* commands with this

2023-05-03 22:31 UTC, dragonmux commented
Excellent, we'll merge this then

2023-05-03 22:31 UTC, merged