Stm32u5 support
blackmagic-debug/blackmagic pull request #1574
Opened 2023-07-28 21:32 UTC by jcamdr

## Detailed description
Addition of the documentation reference for the STM32U5.
Addition of the DP_TARGETIDR id for the STM32U5.
Addition of the stm32l4_device_info for the STM32U5.
Addition of the RAM map for the STM32U5.

## Your checklist for this pull request

* [x] I've read the [Code of Conduct](https://github.com/blackmagic-debug/blackmagic/blob/main/CODE_OF_CONDUCT.md)
* [x] I've read the [guidelines for contributing](https://github.com/blackmagic-debug/blackmagic/blob/main/CONTRIBUTING.md) to this repository
* [x] It builds for hardware native (`make PROBE_HOST=native`)
* [x] It builds as BMDA (`make PROBE_HOST=hosted`)
* [x] I've tested it to the best of my ability
* [x] My commit messages provide a useful short description of what the commits do

## Closing issues

2023-07-29 21:27 UTC, dragonmux requested changes
This is looking great, there's just one tweak that needs making and when done we can then merge this. Thank you for the contribution!

2023-07-29 21:27 UTC, dragonmux commented on src/target/stm32l4.c
> +	if ((device->family == STM32L4_FAMILY_L55x) || (device->family == STM32L4_FAMILY_U5xx))
The parens are unnecessary and suppress a GCC warning about accidental assignment, please drop them:
```suggestion
	if (device->family == STM32L4_FAMILY_L55x || device->family == STM32L4_FAMILY_U5xx)
```

2023-07-30 07:32 UTC, jcamdr commented
I will agree if you ask me to integrate the change request into the second commit. I was not so confident that the operation proposed by the github interface will do that or not.

2023-07-30 07:36 UTC, dragonmux commented
Yes, please do - sorry, meant to get back to this PR earlier and ask you to do just that. With that change made part of the second commit, we're happy to mark as accepted and merge this

2023-07-30 07:39 UTC, jcamdr commented
Don't worry, it's part of the normal learning curve for working together.

2023-07-30 23:57 UTC, dragonmux approved these changes
LGTM now, merging.

2023-07-30 23:57 UTC, merged

2023-07-31 06:29 UTC, jcamdr commented
Thank you!
I will now think about the flash, the biggest part.