Fix revision-reporting command for STM32MP15x
blackmagic-debug/blackmagic pull request #1739
Opened 2024-01-17 20:49 UTC by ALTracer

## Detailed description

* The problem existing approx. since 9a5e3e7b is `monitor revision` failing to report silicon revision of STM32MP15x device.
* This PR solves the immediate minor problem by adjusting the bitshifts in `stm32mp15_cmd_rev()` of DBGMCU_IDCODE to match the DEV_ID value.

Tested on a live device over both DP transports. IDC is 0x20016500.

## Your checklist for this pull request

* [x] I've read the [Code of Conduct](https://github.com/blackmagic-debug/blackmagic/blob/main/CODE_OF_CONDUCT.md)
* [x] I've read the [guidelines for contributing](https://github.com/blackmagic-debug/blackmagic/blob/main/CONTRIBUTING.md) to this repository
* [x] It builds for hardware native (see [Building the firmware](https://github.com/blackmagic-debug/blackmagic?tab=readme-ov-file#building-black-magic-debug-firmware))
* [x] It builds as BMDA (see [Building the BMDA](https://github.com/blackmagic-debug/blackmagic?tab=readme-ov-file#building-black-magic-debug-app))
* [x] I've tested it to the best of my ability
* [x] My commit messages provide a useful short description of what the commits do

## Closing issues

Appending an issue here, in case I manage to fix both.

There is a related issue of MP15x having an erroneous 0x450 ID in JTAG mode matching H74x 0x450 (0x4500) ID in JTAG mode. This manifests as "STM32MP15 M7" detected by BMD instead of "STM32H7 M7" when scanning e.g. a Nucleo-H743ZI2 over 4-wire JTAG (its onboard ST-LINK/V3E is SWD-only). Fixing that involves editing similar IDCODE values in stm32h7.c to match stm32h5.c target driver style, and implementing some actual readout of DBGMCU->IDC for more robust detection, like in `stm32mp15_ident()`. IDC is 0x20016450.
For now I only update `stm32h7_cmd_rev()` to match the two aforementioned drivers of High Performance chips. Because of the way the matching works, I also had to touch a bunch more lines. I'm not sure where does part_id come from depending on the transport used. If this change belongs to a separate PR potentially fully solving the detection problem of H7 (in a way compatible with MP15x due to probing order and multi-AP configuration), then I could rebase/move it out for that.

2024-01-26 17:42 UTC, ALTracer commented
I've started to pile up less related changes to uid commands because I noticed a pattern in half the RMs. This could go into its own PRs; possibly multiple (H7 revision fixes; {MP15 UID refactor; H7 UID refactor} or {common UID refactor} to not make reviewing this more difficult.

2024-01-26 17:51 UTC, dragonmux commented
Think it's fine including them in this PR - just please fix the build issues this now introduces.

We'll try and get this reviewed later today.

2024-01-26 21:02 UTC, dragonmux requested changes
Looking pretty good - there are some review items (based on the comments in the code, ones you were half expecting) and once they're sorted, think this'll be good to merge.

2024-01-30 16:02 UTC, ALTracer commented on src/target/stm32h7.c
> +	const uint16_t part_id = target->part_id >> 4U;
That's a bigger scope suggestion. I only wanted to retain broken detection status but repair `rev` command. Also I can't easily test on all three flavours.

2024-01-30 16:04 UTC, ALTracer commented on src/target/stm32mp15.c
> +		/* XXX: use utoa_upper? */
It's a half-suggestion half-TODO for next time. I don't yet have a good plan to tackle it.

2024-01-30 16:41 UTC, ALTracer commented on src/target/stm32h7.c
> +struct __attribute__((packed)) stm32h7_uid {
Thank you for reviewing this one. To be applied in #1756. I cherry-picked the commits from this branch and pushed without mangling anything so context is preserved (before force-pushes).

2024-01-30 20:44 UTC, dragonmux approved these changes
LGTM, we'll review those new PRs keeping in mind what we've said in the review notes here then and get this merged.

Thank you for the contribution!

2024-01-30 20:44 UTC, merged