Add MSVC and macOS coverage
blackmagic-debug/blackmagic pull request #1748
Opened 2024-01-26 22:43 UTC by amyspark

## Detailed description

This PR implements CI support for MSVC, Apple Xcode, and Homebrewed GCC for macOS.

For the latter two, dependencies are fetched from Homebrew as:

- `libftdi` depends on boost and others to be built from scratch
- GCC cannot build hidapi due to extensive usage of Objective-C constructs

This PR also includes the relevant fixes to make MSVC builds happy, in particular around standards compliance (#1742).

I'm open to any feedback. Let me know what you think!

## Your checklist for this pull request

* [X] I've read the [Code of Conduct](https://github.com/blackmagic-debug/blackmagic/blob/main/CODE_OF_CONDUCT.md)
* [X] I've read the [guidelines for contributing](https://github.com/blackmagic-debug/blackmagic/blob/main/CONTRIBUTING.md) to this repository
* [X] It builds for hardware native (see [Building the firmware](https://github.com/blackmagic-debug/blackmagic?tab=readme-ov-file#building-black-magic-debug-firmware))
* [X] It builds as BMDA (see [Building the BMDA](https://github.com/blackmagic-debug/blackmagic?tab=readme-ov-file#building-black-magic-debug-app))
* [X] I've tested it to the best of my ability
* [X] My commit messages provide a useful short description of what the commits do

## Closing issues

2024-01-26 23:35 UTC, dragonmux requested changes
Only got a couple of notes as this all looks pretty great - with them addressed, this looks good to merge.

2024-01-26 23:35 UTC, dragonmux commented on meson.build
> +# Ensure that MSVC is switched to standards compliant mode
Perhaps better to put this logic in `src/platforms/hosted/meson.build`? That way you can directly fix up `bmda_args` appropriately and use `cc`; It also puts the logic in with the rest of the Windows build logic.

2024-01-26 23:35 UTC, dragonmux commented on src/target/riscv_debug.c
> +		uint32_t isa_data[4] = {0, 0, 0, 0};
Ah, our bad! These are missing `U` on the end of each 0 to match the data type signedness, and you can drop all bar one leaving just `{0U}` if you want (C11 says the implied members are all 0's).

2024-01-26 23:35 UTC, dragonmux commented on src/target/semihosting.c
> +	semihosting_s request = {r1, {0, 0, 0, 0}};
Same comment as riscv_debug.c. The alternative patch (that works for us too) is:
```suggestion
	semihosting_s request = {r1};
```

2024-01-27 01:24 UTC, amyspark reviewed
@dragonmux thanks for the comments! Bits should've been addressed now.

2024-01-27 01:57 UTC, dragonmux approved these changes
LGTM, merging. Thank you for the contribution!

2024-01-27 01:58 UTC, merged