imxrt: Cortex-M4 core detection for RT1176
blackmagic-debug/blackmagic pull request #1913
Opened 2024-08-27 20:05 UTC by litui

## Detailed description

* The i.MX RT1176 includes both an M7 and M4 core but only the M7 was being detected by BMP / BMDA. This fix enables detection of the M4 core (a separate AP entry) under the same target part_id as the M7.
* The generic RAM mapping provided in imxrt.c for all i.MXRT devices was inaccurate for the RT117x and did not distinguish between the memory available to the M7 core vs. the M4 core. This fix maps the RAM based on the target->part_id and core and includes a fairly comprehensive mapping for the RT117x.
* Flash detection logic did not require changing (both cores map the FlexSPI controller at the same location).
* The i.MX RT117x supports register-configurable SDRAM and SRAM but the addresses for this are not fixed and the same controller can be used for flash memory as well. These ranges have been excluded from this fix.
* The [i.MX RT1170 Processor Reference Manual rev 2](https://www.nxp.com/webapp/Download?colCode=IMXRT1170RM) (sign-in required) was used as reference.

## Your checklist for this pull request

* [ ] I've read the [Code of Conduct](https://github.com/blackmagic-debug/blackmagic/blob/main/CODE_OF_CONDUCT.md)
* [ ] I've read the [guidelines for contributing](https://github.com/blackmagic-debug/blackmagic/blob/main/CONTRIBUTING.md) to this repository
* [ ] It builds for hardware native (see [Building the firmware](https://github.com/blackmagic-debug/blackmagic?tab=readme-ov-file#building-black-magic-debug-firmware))
* [ ] It builds as BMDA (see [Building the BMDA](https://github.com/blackmagic-debug/blackmagic?tab=readme-ov-file#building-black-magic-debug-app))
* [ ] I've tested it to the best of my ability
* [ ] My commit messages provide a useful short description of what the commits do

## Closing issues

2024-08-27 20:12 UTC, litui commented
Tested using a Google Coral Micro dev board running its `multi_core_hello` example (the M4 core has to be switched on for it to be detected).

2024-09-10 05:02 UTC, dragonmux requested changes
This is looking very good. We have a couple of queries, but once they've been addressed we'll be happy to get this merged.

2024-09-10 05:02 UTC, dragonmux commented on src/target/imxrt.c
> +#define IMXRT117x_SYS_TCM_SIZE    0x00020000U
Due to how the TCMs work, we had intentionally omitted them from the memory maps before. Are they necessary for breakpoints to work properly, or can they remain omitted on account of faulting till enabled and not being readable in all situations when they are?

2025-01-16 20:18 UTC, litui commented on src/target/imxrt.c
> +#define IMXRT117x_SYS_TCM_SIZE    0x00020000U
Probably not necessary for now. Removed TCMs.

2025-01-16 20:21 UTC, dragonmux submitted a review, later dismissed
LGTM, merging once the build failing item is fixed. Thank you for the contribution!

2025-01-16 20:23 UTC, dragonmux approved these changes

2025-01-16 20:32 UTC, merged