Arm cortexm: Temptative  fix for watchpoints so they work on  v8m arch ( CM33)
blackmagic-debug/blackmagic pull request #2008
Opened 2024-11-30 14:30 UTC by mean00

## Detailed description

The DWT block is different on Arm V8m compared to older revisions.  As a result the watchpoint(s) function are not working. 
The patch adds a second path dealing with the ArmV8m  .
Tested on cortex m33, check setup watch some_variable  (such as xTickCount on freeRtos)
- without the patch, does not stop
- with the patch, does stop as expected

It was partially tested, i dont have other chip with that DWT block. Only test write watchpoints.
As far as i can tell, watchpoints are still working with older chips (cortex M4)

## Your checklist for this pull request

* [X ] I've read the [Code of Conduct](https://github.com/blackmagic-debug/blackmagic/blob/main/CODE_OF_CONDUCT.md)
* [ X] I've read the [guidelines for contributing](https://github.com/blackmagic-debug/blackmagic/blob/main/CONTRIBUTING.md) to this repository
* [ X] It builds for hardware native (see [Building the firmware](https://github.com/blackmagic-debug/blackmagic?tab=readme-ov-file#building-black-magic-debug-firmware))
* [ X] It builds as BMDA (see [Building the BMDA](https://github.com/blackmagic-debug/blackmagic?tab=readme-ov-file#building-black-magic-debug-app))
* [ X] I've tested it to the best of my ability
* [ ] My commit messages provide a useful short description of what the commits do

## Closing issues

2024-12-02 15:07 UTC, dragonmux requested changes
This is looking really good and complements our own work on ARMv8-M debug on the fix branch `fix/adi-structural-cleanup`. We'd love to get this merged for v2.0 so if you can take care of the small number of review notes (most are to do with nomenclature and we don't think will take that long to deal with as it's mostly just find-replace stuff), we'll get this merged ASAP.

2024-12-02 15:07 UTC, dragonmux commented on src/target/cortexm.c
> +	uint32_t x = CORTEXM_DWT_FUNC_ACTION_DEBUG_EVENT_V8M;
Please don't use single letter variable names - something like `result` or `func` would be better here. Thank you for using `uint32_t` though!

2024-12-02 15:07 UTC, dragonmux commented on src/target/cortexm.c
> +		return -1;
This does an implementation defined conversion, please use `UINT32_MAX` instead or a result like `0U` for less code generation.

2024-12-02 15:07 UTC, dragonmux commented on src/target/cortexm.c
> +static uint32_t cortexm_dwt_func_v8m(target_s *target, target_breakwatch_e type, size_t len)
Similar comment as in the header about `_v8m` vs `dwtv2` - please prefer the latter.

2024-12-02 15:08 UTC, dragonmux commented on src/target/cortexm.c
> +	default:
There's a missing `break;` before this, which is what's got CI hung up.

2024-12-03 06:06 UTC, mean00 commented
Thank you for the comments, will update it as soon as i can

2024-12-04 06:25 UTC, mean00 commented
I think i took all the comments into account.
If it's ok i'll squash the commits
Thank you

2024-12-04 08:31 UTC, dragonmux approved these changes
Yeah, looks good to us. Please let us know once you've squashed the commits down (noting that there should not be a space between the suffix and its' `:`, so `cortexm:` not `cortexm :`) and we'll get this merged.

Thank you for the contribution! Nicely done.

2024-12-04 19:02 UTC, mean00 commented
Should be okay now
Thank you

2024-12-04 20:23 UTC, dragonmux approved these changes

2024-12-04 20:36 UTC, merged